apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-provider-secret
type: Opaque
data:
  credentials: QkFTRTY0RU5DT0RFRF9QUk9WSURFUl9DUkVEUwo=
---
apiVersion: sonarqube.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
  namespace: default
spec:
  baseURL: http://sonarqube.example.com/api
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
---
apiVersion: sonarqube.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: example
spec:
  baseURL: http://sonarqube.example.com/api
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
